language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

install:
  - git submodule update --remote --merge
  - cd pystocktwits && python setup.py install
  - cd ../ && python setup.py install
  - pip install textblob

script:
  - python tests/pystocktwits_data_utils_tests.py
